# Generated by Django 3.1.7 on 2021-05-07 12:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import scanner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New configuration', max_length=50)),
                ('web_discovery', models.BooleanField(default=False)),
                ('port_scan', models.BooleanField(default=False)),
                ('subdomain_discovery', models.BooleanField(default=True)),
                ('vulnerability_scan', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(default='', max_length=100)),
                ('open_ports', models.CharField(default='', max_length=500)),
                ('start_domain', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_status', models.IntegerField(null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('port', models.IntegerField(null=True)),
                ('web_title', models.CharField(max_length=500, null=True)),
                ('cname', models.CharField(max_length=500, null=True)),
                ('server', models.CharField(max_length=500, null=True)),
                ('content_length', models.IntegerField(null=True)),
                ('screenshot_path', models.CharField(max_length=200, null=True)),
                ('technologies', models.CharField(max_length=500, null=True)),
                ('discovered_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='scanner.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('page', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(max_length=100, null=True)),
                ('template', models.CharField(max_length=500, null=True)),
                ('protocol', models.CharField(max_length=200, null=True)),
                ('extractor', models.CharField(max_length=500, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanner.webhost')),
            ],
            options={
                'verbose_name_plural': 'Vulnerabilities',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=100)),
                ('scan_status', models.CharField(choices=[(scanner.models.ScanStatus['NEVER_SCANNED'], 'Never scanned'), (scanner.models.ScanStatus['SCANNING'], 'Scanning'), (scanner.models.ScanStatus['ERROR'], 'Error'), (scanner.models.ScanStatus['FINISHED'], 'Finished scan')], default=scanner.models.ScanStatus['NEVER_SCANNED'], max_length=100)),
                ('last_scan_date', models.DateTimeField(null=True)),
                ('last_error_log', models.CharField(default='', max_length=500)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.configuration')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.scan'),
        ),
    ]
