# Generated by Django 3.1.5 on 2021-02-16 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import scanner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New configuration', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('port_scan', models.BooleanField(default=False)),
                ('subdomain_discovery', models.BooleanField(default=True)),
                ('vulnerability_scan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.CharField(max_length=100)),
                ('open_ports', models.CharField(max_length=100)),
                ('start_domain', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_status', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('port', models.IntegerField()),
                ('web_title', models.CharField(max_length=500)),
                ('content_length', models.IntegerField()),
                ('screenshot_path', models.CharField(max_length=200)),
                ('discovered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[(scanner.models.RiskLevel['LOW'], 'Low'), (scanner.models.RiskLevel['MODERATE'], 'Moderate'), (scanner.models.RiskLevel['HIGH'], 'High'), (scanner.models.RiskLevel['CRITICAL'], 'Critical')], default=scanner.models.RiskLevel['LOW'], max_length=100)),
                ('vuln_type', models.CharField(choices=[(scanner.models.VulnerabilityType['DEFAULT'], ''), (scanner.models.VulnerabilityType['XSS'], 'Cross site scripting'), (scanner.models.VulnerabilityType['SQLINJECTION'], 'SQL Injection'), (scanner.models.VulnerabilityType['DNS'], 'Denial of Service')], default=scanner.models.VulnerabilityType['DEFAULT'], max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.webhost')),
            ],
            options={
                'verbose_name_plural': 'Vulnerabilities',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=100)),
                ('scan_status', models.CharField(choices=[(scanner.models.ScanStatus['NEVER_SCANNED'], 'Never scanned'), (scanner.models.ScanStatus['SCANNING'], 'Scanning'), (scanner.models.ScanStatus['FINISHED'], 'Finished scan')], default=scanner.models.ScanStatus['NEVER_SCANNED'], max_length=100)),
                ('last_scan_date', models.DateTimeField()),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.configuration')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.scan'),
        ),
    ]
