# Generated by Django 3.1.7 on 2021-05-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.scan'),
        ),
        migrations.AddField(
            model_name='webhost',
            name='scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scanner.scan'),
        ),
    ]
