# Generated by Django 3.1.5 on 2021-02-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='last_scan_date',
            field=models.DateTimeField(null=True),
        ),
    ]
