# Generated by Django 3.1.5 on 2021-02-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_auto_20210216_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
