# Generated by Django 3.1.7 on 2021-04-01 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_auto_20210330_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scanner.webhost'),
        ),
        migrations.AlterField(
            model_name='webhost',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='scanner.domain'),
        ),
    ]
