# Generated by Django 3.1.7 on 2021-05-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_auto_20210531_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='tool_amass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='tool_assetfinder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='tool_subfinder',
            field=models.BooleanField(default=False),
        ),
    ]
