# Generated by Django 3.1.7 on 2021-06-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_auto_20210531_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='current_thread',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
