# Generated by Django 3.1.7 on 2021-04-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_auto_20210403_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhost',
            name='technologies',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
