# Generated by Django 3.1.7 on 2021-04-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0005_webhost_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='open_ports',
            field=models.CharField(default='', max_length=500),
        ),
    ]
