# Generated by Django 3.1.5 on 2021-03-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0006_auto_20210307_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhost',
            name='cname',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webhost',
            name='server',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
