# Generated by Django 3.1.7 on 2021-04-22 17:36

from django.db import migrations, models
import scanner.models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_auto_20210421_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='last_error_log',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_status',
            field=models.CharField(choices=[(scanner.models.ScanStatus['NEVER_SCANNED'], 'Never scanned'), (scanner.models.ScanStatus['SCANNING'], 'Scanning'), (scanner.models.ScanStatus['ERROR'], 'Error'), (scanner.models.ScanStatus['FINISHED'], 'Finished scan')], default=scanner.models.ScanStatus['NEVER_SCANNED'], max_length=100),
        ),
    ]
