# Generated by Django 3.1.7 on 2021-04-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_auto_20210422_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='page',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
